### PR TITLE
List namespaces

### PR DESCRIPTION
**Pull request by abrochard**

### CODE REVIEW

**Comment by CsBigDataHub** [comment]
Really useful feature, used to use in `Kubernetes.el`

**Comment by abrochard** [comment]
I want to finish and merge soon but I am conflicted. The main reason I started kubel is because I didn't have permissions in the cluster to list namespaces. Now I have them. 

However I have doubts on how to release that feature:
- if I enable it by default, I might break users who like me didn't have the permissions and they will have to manually turn it off
- if I don't enable it by default, users who might get a big benefit from it might not enable it and miss it
- I could try to find a way to determine if the users has permissions and enable it dynamically but idk how

@CsBigDataHub do you have any suggestions?

**Comment by CsBigDataHub** [comment]
@abrochard I have been using [kubernetes.el](https://github.com/chrisbarrett/kubernetes-el)for a while now. At work I have on-prem kubernetes cluster and we also use Azure AKS. Everywhere I am able to list name spaces. Even though if you do not have permission `kubectl list namespaces` will just return the list you have access to.

This is a very useful feature while switching namespaces, you will be able to select desired option rather that having to type the name of the namespace.

**Comment by abrochard** [comment]
@CsBigDataHub that's not exactly the problem I was trying to explain. 

Just running `kubectl list namespaces` requires some level of permissions on the cluster that all users may not have. This is why originally kubel only supported switching namespaces by typing the namespace name.

I think I am going to use the `can-i` syntax to do a smart rollout of the new feature: `kubectl auth can-i list namespaces` will inform whether or not the feature is enabled.

**Comment by CsBigDataHub** [comment]
> @CsBigDataHub that's not exactly the problem I was trying to explain. 
> 
> Just running `kubectl list namespaces` requires some level of permissions on the cluster that all users may not have. This is why originally kubel only supported switching namespaces by typing the namespace name.
> 
> I think I am going to use the `can-i` syntax to do a smart rollout of the new feature: `kubectl auth can-i list namespaces` will inform whether or not the feature is enabled.

Thanks @abrochard  that makes sense.

**Pull request merged**
